# -*- coding: utf-8 -*-
"""Parshav_My_Simple_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raCHj5RCGFvrsgcYVa3HucRolO9ivAnI

Step 1: Install required packages
"""

!pip install google-generativeai --quiet
!pip install ipywidgets --quiet #create beautiful UI

"""Step 2: Import libraries"""

import google.generativeai as genai
import ipywidgets as widgets
from IPython.display import display, Markdown

"""Step 3: Set up Gemini API"""

API_KEY = "AIzaSyDSQYu2SzCdZQvhJm6BL6vwyZNfJHhkbaU"
genai.configure(api_key= API_KEY),
model = genai.GenerativeModel("gemini-2.5-flash")

"""Step 4: Define the input form"""

topic_input = widgets.Text(
    description = "TOPIC",
    layout = widgets.widgets.Layout( width = "400px"))

tone_input = widgets.Dropdown(
    description = "TONE",
    options = ['witty', 'casual', 'normal', 'proffesional', 'angry', 'sarcastic'],
    layout = widgets.widgets.Layout( width = "400px")
)

audience_input = widgets.Text(
    description = "AUDIENCE",
    layout = widgets.widgets.Layout( width = "400px")
)

hastag_input = widgets.Text(
    description = "HASHTAGS",
    layout = widgets.widgets.Layout( width = "400px")
)

submit_button = widgets.Button(
    description = "Generate Tweet",
    button_style = 'Success',
    tooltip = 'click to generate tweet',
    layout = widgets.Layout( width = "400px")
)

output = widgets.Output()

"""Step 5: Generate Tweet Function"""

def generate_tweet(b):
  output.clear_output()
  prompt = f"""
      You are an expert Content writer.
      generate a tweet about the topic "{topic_input.value}".
      use a ton {tone_input.value}.
      generate tweet for audience {audience_input.value}.
      also include the hashtag {hastag_input.value}.
      keep it under 100 words.
  """

  with output:
    try:
      response = model.generate_content(prompt)
      tweet = response.text.strip()
      display(Markdown(f"## Generated Tweet: \n\n{tweet}"))
    except Exception as e:
      print("Error: ", e)

submit_button.on_click(generate_tweet)

"""Step 6: Display the form"""

form = widgets.VBox([
    widgets.HTML(value= "<h3>Agent to Generate Tweet </h3>"),
    topic_input,
    tone_input,
    audience_input,
    hastag_input,
    submit_button,
    output
])

display(form)